config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#show'

  resources :seats, only: %i[index update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/seat.rb
class Seat < ApplicationRecord
  scope :taken, -> { where(taken: true) }
  scope :not_taken, -> { where(taken: false) }

  def take
    update!(taken: true)
  end

  def untake
    update!(taken: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @seats = Seat.not_taken
  end
end

app/controllers/seats_controller.rb
# frozen_string_literal: true

class SeatsController < ApplicationController
  def update
    @seat = Seat.find(params[:id])

    return redirect_to root_path if !@seat.taken && @seat.take

    flash[:error] = 'Seat is already taken'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/home/show.html.erb
<div>
  <h1 class="font-bold text-4xl mb-5">Select a seat</h1>

  <% if flash[:error] %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Error!</strong>
      <span class="block sm:inline"><%= flash[:error] %></span>
    </div>
  <% end %>

  <div id="seats" class="flex">
    <% @seats.each do |seat| %>
      <%= form_with model: seat, url: seat_path(seat), method: :put do |f|  %>
        <div class="w-10 h-10 bg-gray-200 mx-3 text-center cursor-pointer">
          <%= f.submit seat.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locking Program</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/seats/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Seats#update</h1>
  <p>Find me in app/views/seats/update.html.erb</p>
</div>